---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-printing-service
  labels:
    app: simple-printing-service
spec:
  selector:
    matchLabels:
      app: simple-printing-service
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-printing-service
    spec:
      containers:
      - name: simple-printing-service
        image: mapmo/simple_printing_service:0.0.6
        imagePullPolicy: Always
        env:
          - name: DEFAULT
            value: K8S default
        command: ["python", "simple_printing_service.py", "-i", "1"]
        livenessProbe:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "ps aux | grep simple_printing_service.py | grep -qv grep"
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 1
        lifecycle:
          preStop:
            exec:
              command: ["pkill", "python"]
---
apiVersion: v1
kind: Service
metadata:
  name: simple-printing-service
spec:
  selector:
    app: simple-printing-service
  ports:
    - name: simple-printing-service
      port: 3000
